// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jremlnyshenzrtysacck.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpyZW1sbnlzaGVuenJ0eXNhY2NrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2OTgxOTYsImV4cCI6MjA2MTI3NDE5Nn0.OzIjrxZyT5OpOf8p5FQPrduocQkX7jKS3d_ZRaomGn0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);